/* config_nc.h.  Generated by configure.  */
/* config_nc.h.in.  Generated from configure.ac by autoheader.  */

#ifndef _config_nc_h
#define _config_nc_h

#define NETCDF_VERSION 4

/* Shorthand for gcc's unused attribute feature */
#if defined(__GNUG__) || defined(__GNUC__)
#define not_used __attribute__ ((unused))
#else
#define not_used
#endif /* __GNUG__ || __GNUC__ */

#endif /* _config_nc_h */
